// Generated by `sproutboat types`. Do not edit.
//
// Regenerated whenever sproutboat.jsonc is newer than this file, so a binding
// added to the config shows up in the editor without asking. Commit it: it is
// part of the project's type surface, like a schema.

/// <reference types="sproutboat/types" />

declare global {
  /**
   * Bindings from sproutboat.jsonc, for project "risulta-sprout".
   *
   * The handler signature is fetch(request, ctx); env is only a global.
   * Every call on these is synchronous, so `await` is allowed and does
   * nothing.
   */
  const env: {
    /** vars: "Risulta Sprout" */
    SITE_NAME: string;
    /** secret, set with `sproutboat secrets put` */
    RISULTA_ADMIN_EMAIL: string;
    /** secret, set with `sproutboat secrets put` */
    RISULTA_ADMIN_DISPLAY_NAME: string;
    /** secret, set with `sproutboat secrets put` */
    RISULTA_ADMIN_PASSWORD: string;
    /** secret, set with `sproutboat secrets put` */
    RISULTA_BASE_URL: string;
    /** secret, set with `sproutboat secrets put` */
    RISULTA_LOG_LEVEL: string;
    DB: D1Database;
    /** rate limit: 240 per 60s */
    INGEST: RateLimit;
    /** static assets: public */
    ASSETS: Fetcher;
  };
}

export {};
