import assert from 'node:assert/strict';
import { Database } from 'bun:sqlite';
import { ANNOTATION_SCHEMA, annotationInput, siteAnnotations } from '../src/annotations.js';
import { chart } from '../src/chart.js';
import { setupPage, trackerStatus, siteSettingsPage } from '../src/views.js';
const sqlite = new Database(':memory:');
sqlite.exec('CREATE TABLE sites(id INTEGER PRIMARY KEY);INSERT INTO sites VALUES(1),(2);' + ANNOTATION_SCHEMA);
const db = {prepare(sql) { const query=sqlite.query(sql);let args=[];return {bind(...values){args=values;return this;},all(){return {results:query.all(...args)};}};}};
const note = annotationInput({day:'2026-10-09',text:' New homepage <launch> '});
assert.equal(note.text,'New homepage <launch>');
for(const day of ['2026-02-30','2026-13-01','1999-01-01','not-a-date']) assert.ok(annotationInput({day,text:'x'}).error);
assert.ok(annotationInput({day:'2026-10-09',text:' '}).error);
assert.ok(annotationInput({day:'2026-10-09',text:'x'.repeat(241)}).error);
sqlite.query('INSERT INTO annotations(site_id,ts,text) VALUES(?,?,?)').run(1,note.ts,note.text);
sqlite.query('INSERT INTO annotations(site_id,ts,text) VALUES(?,?,?)').run(2,note.ts,'Private other site');
const notes=siteAnnotations(db,1,{since:note.ts,until:note.ts+86400});
assert.equal(notes.length,1);assert.equal(notes[0].day,note.day);
assert.equal(siteAnnotations(db,1,{since:note.ts+86400,until:note.ts+172800}).length,0);
const svg=chart([{day:note.day,visitors:5}], 'visitors','Visitors',false,notes);
assert.ok(svg.includes('chart-annotation'));assert.ok(svg.includes('New homepage &lt;launch&gt;'));
assert.ok(!svg.includes('Private other site'));
const site={id:1,slug:'example',name:'Example',domain:'example.test',public_key:'key'};
const user={role:'admin',csrf:'token',email:'admin@example.test'};
const waiting=setupPage(user,site,[site],'https://stats.example.test',false);
assert.ok(waiting.includes('Waiting for your first pageview.'));assert.ok(waiting.includes('https://stats.example.test/js/key.js'));
assert.ok(trackerStatus(site,true).includes('Your tracker is connected.'));
assert.ok(!trackerStatus(site,true).includes('hx-trigger'));
const settings=siteSettingsPage(user,site,[site],'',false,{enabled:1},'https://stats.example.test',notes,{size:'wide',theme:'dark'});
assert.ok(settings.includes('data-size=&quot;wide&quot;'));assert.ok(settings.includes('Copy embed code'));assert.ok(settings.includes('/annotations/1/delete'));
assert.ok(!siteSettingsPage({...user,role:'viewer'},site,[site],'',false,{enabled:1},'https://stats.example.test',notes).includes('/annotations/1/delete'));
sqlite.close();
console.log('Annotations and setup markup OK (validation, date boundaries, isolation, escaped notes, completed setup and admin controls)');
