import { ROLLUP_SCHEMA, STATS_ROLLUP_SCHEMA } from '../src/rollups.ts';
import assert from 'node:assert/strict';
import { Database } from 'bun:sqlite';
import { overviewScope, siteAnalytics, siteSummary, siteReport } from '../src/store.js';
import { siteJourneys } from '../src/journeys.js';
import { overviewAnalytics, overviewComparison, invalidateOverview, measurementAnalytics, reportAnalytics, journeyAnalytics } from '../src/overview.js';
import { liveFragment, sitePage } from '../src/views.js';
const sqlite = new Database(':memory:');
sqlite.exec(`CREATE TABLE events(id INTEGER PRIMARY KEY,site_id INTEGER,ts INTEGER,name TEXT,path TEXT,visitor TEXT,source TEXT,medium TEXT,campaign TEXT,value REAL);
CREATE TABLE goals(id INTEGER PRIMARY KEY,site_id INTEGER,name TEXT,event_name TEXT,path TEXT);
CREATE TABLE funnels(id INTEGER PRIMARY KEY,site_id INTEGER,name TEXT);`);
sqlite.exec(ROLLUP_SCHEMA + STATS_ROLLUP_SCHEMA);
const db = { prepare(sql) { return { bind(...args) { return { first() { return sqlite.query(sql).get(...args); }, all() { return { results: sqlite.query(sql).all(...args) }; } }; } }; } };
const insert = sqlite.query('INSERT INTO events VALUES(?,?,?,?,?,?,?,?,?,?)');
insert.run(1,1,100,'pageview','/landing','a','Google','organic','launch',null);
insert.run(2,1,120,'pageview','/pricing','a','','','',null);
insert.run(3,1,150,'signup','/thanks','a','','','',null);
insert.run(4,1,200,'pageview','/landing','b','Bing','organic','',null);
insert.run(5,2,110,'pageview','/other','a','Google','organic','launch',null);
sqlite.exec("INSERT INTO goals VALUES(1,1,'Signup','signup',''),(2,1,'Purchase','purchase','')");
const scoped = overviewScope(db,1,0,1000,{source:'Google'});
const analytics = siteAnalytics(scoped,{id:1},0,1000,false);
assert.deepEqual(analytics.summary,{pageviews:2,visitors:1,visits:1});
assert.deepEqual(siteSummary(scoped,1,0,1000),analytics.summary);
assert.equal(analytics.goals[0].conversions,1);
assert.equal(analytics.goals[0].conversion_rate,1);
assert.equal(analytics.goals[1].conversions,0);
assert.equal(analytics.funnels.length,0);
assert.equal(siteJourneys(scoped,1,0,1000,{visitor:"",limit:10,offset:0}).rows.length,1);
assert.equal(siteJourneys(scoped,1,0,1000,{visitor:"",limit:10,offset:0}).rows[0].events.length,3);
assert.equal(siteReport(scoped,1,0,1000,'path',{},5,0,'visitors').total,2);
assert.equal(siteAnalytics(overviewScope(db,1,0,1000,{source:"' OR 1=1 --"}),{id:1},0,1000,false).summary.pageviews,0);
assert.equal(siteAnalytics(overviewScope(db,1,0,1000,{source:'Google',path:'/missing'}),{id:1},0,1000,false).summary.visitors,0);
assert.equal(siteAnalytics(overviewScope(db,1,0,1000,{source:'Google',path:'/pricing'}),{id:1},0,1000,false).summary.visitors,1);
const range={since:0,until:1000,from:'1970-01-01',to:'1970-01-01',filters:{source:'Google'},acquisition:'campaign'};
const html=liveFragment({id:1},analytics,range,1,'visitors',null);
assert.ok(html.includes('Goals'));
assert.ok(html.includes('hx-target="this"'));
assert.ok(html.includes('Remove source filter: Google'));
assert.ok(html.includes('source=Google'));
assert.ok(html.includes('cohort=1'));
assert.ok(!html.includes('data-disclosure="conversions"'));
assert.ok(!html.includes('data-disclosure="campaigns"'));
const page=sitePage({role:'admin',email:'demo@example.com',csrf:'x'},{id:1,name:'Demo',domain:'example.com',public_key:'x'},[],analytics,range,1,'visits','http://localhost',null);
assert.match(page,/data-stats-url="[^"]*source=Google/);
assert.match(page,/name="source" value="Google"/);
const compared = liveFragment({id:1},{...analytics,summary:{visitors:123,visits:1,pageviews:0}},range,1,'visitors',{visitors:50,visits:0,pageviews:5});
assert.ok(compared.includes('>+146%</span>'));
assert.ok(compared.includes('>-100%</span>'));
assert.ok(compared.includes('>New</span>'));
assert.ok(!compared.includes('Infinity'));
const comparedPage = sitePage({role:'admin',email:'demo@example.com',csrf:'x'},{id:1,name:'Demo',domain:'example.com',public_key:'x'},[],analytics,range,1,'visits','http://localhost',analytics.summary);
assert.ok(!comparedPage.includes('comparison-control'));
assert.ok(!comparedPage.includes('Hide comparison'));
assert.ok(!comparedPage.includes('Compare previous period'));
assert.ok(comparedPage.includes('>0%</span>'));
// Snapshots share work across metrics while respecting filters, DBs and expiry.
let reads = 0;
const counted = { prepare(sql) { reads++; return db.prepare(sql); } };
const liveRange = { since: 0, until: 1001, days: 7, filters: {} };
const first = overviewAnalytics(counted, { id: 1 }, liveRange, true, 1000000);
const initialReads = reads;
const warm = overviewAnalytics(counted, { id: 1 }, { ...liveRange, until: 1002 }, true, 1001000);
assert.equal(reads, initialReads);
assert.deepEqual(warm.summary, first.summary);
assert.deepEqual(warm.byHour, []);
assert.equal(overviewAnalytics(counted, { id: 1 }, liveRange, false, 1001000).goals.length, 0);
assert.equal(first.goals.length, 2);
overviewAnalytics(counted, { id: 1 }, { ...liveRange, filters: {source:'Google'} }, true, 1001000);
assert.ok(reads > initialReads);
let before = reads;
overviewAnalytics(counted, { id: 2 }, liveRange, true, 1001000);
assert.ok(reads > before);
before = reads;
overviewAnalytics(counted, { id: 1 }, { ...liveRange, until: 1021 }, false, 1020000);
assert.ok(reads > before);
before = reads;
invalidateOverview(counted, 1);
overviewAnalytics(counted, { id: 1 }, liveRange, true, 1000000);
assert.ok(reads > before);
// Goal snapshots expire independently, including for fixed historical ranges.
const historyRange = { since: 0, until: 1000, days: 7, from: '1970-01-01', filters: {} };
invalidateOverview(counted, 1);
overviewAnalytics(counted, {id:1}, historyRange, true, 1000000);
sqlite.exec("INSERT INTO events VALUES(6,1,160,'signup','/thanks','a','','','',NULL)");
assert.equal(overviewAnalytics(counted,{id:1},historyRange,true,1016000).goals[0].conversions,1);
assert.equal(overviewAnalytics(counted,{id:1},historyRange,true,1060000).goals[0].conversions,2);
assert.ok(overviewAnalytics(counted,{id:1},{...liveRange,days:1},false,1100000).byHour.length > 0);
const otherDb = { prepare(sql) { reads++; return db.prepare(sql); } };
before = reads;
overviewAnalytics(otherDb, { id: 1 }, liveRange, true, 1000000);
assert.ok(reads > before);
const previousRange = {since:0,until:1000,filters:{}};
overviewComparison(counted,{id:1},previousRange,1000000);
before = reads;
overviewComparison(counted,{id:1},previousRange,1001000);
assert.equal(reads,before);
// Bounded snapshots evict old ranges rather than growing with arbitrary filters.
for (let i=0;i<33;i++) overviewAnalytics(counted,{id:1},{since:0,until:1000,filters:{path:'/cache-'+i}},false,1000000);
before = reads;
overviewAnalytics(counted,{id:1},liveRange,true,1000000);
assert.ok(reads>before);
invalidateOverview(counted,1);
const measurement = measurementAnalytics(counted,{id:1},historyRange,'goals',1000000);
before = reads;
assert.deepEqual(measurementAnalytics(counted,{id:1},historyRange,'goals',1001000),measurement);
assert.equal(reads,before);
measurementAnalytics(counted,{id:1},historyRange,'goals',1015000);
assert.ok(reads>before);

// Report pagination performs one aggregation and keeps exact totals on empty pages.
const input = {dimension:'path',filters:{},limit:1,offset:0,sort:'visitors'};
invalidateOverview(counted,1);
before = reads;
const report = reportAnalytics(counted,{id:1},historyRange,input,false,1000000);
assert.equal(reads-before,1);
assert.equal(report.total,2);
assert.equal(report.rows.length,1);
before = reads;
assert.deepEqual(reportAnalytics(counted,{id:1},historyRange,input,false,1001000),report);
assert.equal(reads,before);
assert.equal(reportAnalytics(counted,{id:1},historyRange,{...input,offset:10},false,1001000).total,2);
assert.equal(reportAnalytics(counted,{id:2},historyRange,input,false,1001000).total,1);
assert.equal(reportAnalytics(counted,{id:1},{...historyRange,filters:{source:'Google'}},{...input,filters:{source:'Google'}},true,1001000).total,2);
before = reads;
reportAnalytics(counted,{id:1},historyRange,input,false,1015000);
assert.ok(reads>before);
const journeyInput={visitor:'',limit:1,offset:0};
const journey=journeyAnalytics(counted,{id:1},historyRange,journeyInput,1000000);
before=reads;
assert.deepEqual(journeyAnalytics(counted,{id:1},historyRange,journeyInput,1001000),journey);
assert.equal(reads,before);
assert.equal(journeyAnalytics(counted,{id:1},historyRange,{...journeyInput,offset:1},1001000).rows.length,1);
assert.ok(html.includes('id="sources"'));
assert.ok(html.includes('id="campaigns"'));
assert.ok(html.includes('id="mediums"'));
assert.ok(!html.includes('data-acquisition-panel'));
assert.match(html, /class="report-head"><h2 id="goals-title">Goals<\/h2><a class="report-link"/);
assert.ok(page.includes('hx-boost:inherited="swap:&quot;outerSync show:none&quot; select:#main target:#main"'));
sqlite.close();
console.log('overview OK (visitor cohorts, cross-site isolation, goal previews, zero goals, safe filters and context)');
