import assert from 'node:assert/strict';
import { Database } from 'bun:sqlite';
import { overviewScope, siteAnalytics, siteSummary, siteReport } from '../src/store.js';
import { siteJourneys } from '../src/journeys.js';
import { liveFragment, sitePage } from '../src/views.js';
const sqlite = new Database(':memory:');
sqlite.exec(`CREATE TABLE events(id INTEGER PRIMARY KEY,site_id INTEGER,ts INTEGER,name TEXT,path TEXT,visitor TEXT,source TEXT,medium TEXT,campaign TEXT,value REAL);
CREATE TABLE goals(id INTEGER PRIMARY KEY,site_id INTEGER,name TEXT,event_name TEXT,path TEXT);
CREATE TABLE funnels(id INTEGER PRIMARY KEY,site_id INTEGER,name TEXT);`);
const db = { prepare(sql) { return { bind(...args) { return { first() { return sqlite.query(sql).get(...args); }, all() { return { results: sqlite.query(sql).all(...args) }; } }; } }; } };
const insert = sqlite.query('INSERT INTO events VALUES(?,?,?,?,?,?,?,?,?,?)');
insert.run(1,1,100,'pageview','/landing','a','Google','organic','launch',null);
insert.run(2,1,120,'pageview','/pricing','a','','','',null);
insert.run(3,1,150,'signup','/thanks','a','','','',null);
insert.run(4,1,200,'pageview','/landing','b','Bing','organic','',null);
insert.run(5,2,110,'pageview','/other','a','Google','organic','launch',null);
sqlite.exec("INSERT INTO goals VALUES(1,1,'Signup','signup',''),(2,1,'Purchase','purchase','')");
const scoped = overviewScope(db,1,0,1000,{source:'Google'});
const analytics = siteAnalytics(scoped,{id:1},0,1000,false);
assert.deepEqual(analytics.summary,{pageviews:2,visitors:1,visits:1});
assert.deepEqual(siteSummary(scoped,1,0,1000),analytics.summary);
assert.equal(analytics.goals[0].conversions,1);
assert.equal(analytics.goals[0].conversion_rate,1);
assert.equal(analytics.goals[1].conversions,0);
assert.equal(analytics.funnels.length,0);
assert.equal(siteJourneys(scoped,1,0,1000,{visitor:"",limit:10,offset:0}).rows.length,1);
assert.equal(siteJourneys(scoped,1,0,1000,{visitor:"",limit:10,offset:0}).rows[0].events.length,3);
assert.equal(siteReport(scoped,1,0,1000,'path',{},5,0,'visitors').total,2);
assert.equal(siteAnalytics(overviewScope(db,1,0,1000,{source:"' OR 1=1 --"}),{id:1},0,1000,false).summary.pageviews,0);
assert.equal(siteAnalytics(overviewScope(db,1,0,1000,{source:'Google',path:'/missing'}),{id:1},0,1000,false).summary.visitors,0);
assert.equal(siteAnalytics(overviewScope(db,1,0,1000,{source:'Google',path:'/pricing'}),{id:1},0,1000,false).summary.visitors,1);
const range={since:0,until:1000,from:'1970-01-01',to:'1970-01-01',filters:{source:'Google'},acquisition:'campaign'};
const html=liveFragment({id:1},analytics,range,1,'visitors',null);
assert.ok(html.includes('Goals'));
assert.ok(html.includes('hx-target="this"'));
assert.ok(html.includes('Remove source filter: Google'));
assert.ok(html.includes('source=Google'));
assert.ok(html.includes('cohort=1'));
assert.ok(!html.includes('data-disclosure="conversions"'));
assert.ok(!html.includes('data-disclosure="campaigns"'));
const page=sitePage({role:'admin',email:'demo@example.com',csrf:'x'},{id:1,name:'Demo',domain:'example.com',public_key:'x'},[],analytics,range,1,'visits','http://localhost',null);
assert.match(page,/data-stats-url="[^"]*source=Google/);
assert.match(page,/name="source" value="Google"/);
sqlite.close();
console.log('overview OK (visitor cohorts, cross-site isolation, goal previews, zero goals, safe filters and context)');
